version: '{build}'

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  python_exe: C:\Python36-x64\python.exe
  install_dir: C:\Projects\install\privilege-check

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - '"%python_exe%" cmake\cmake\build\ci\appveyor.py --install "%install_dir%"'

after_build:
  - 7z.exe a "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%.zip" "%install_dir%"
  - appveyor.exe PushArtifact "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%.zip"

for:
# Only build Release builds for master to speed things up:
- branches:
    except:
      - master
  configuration:
    - Debug
