name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        toolset: [mingw, vs2015, vs2017, vs2019]
        platform: [x64, x86]
        configuration: [Debug, Release]
        include:
          # MinGW builds are done on Linux, since it's more up-to-date there,
          # and it's much faster.
          - {toolset: mingw, os: ubuntu-latest}
          - {toolset: vs2015, os: windows-2016}
          - {toolset: vs2017, os: windows-2016}
          - {toolset: vs2019, os: windows-2019}
    runs-on: '${{ matrix.os }}'
    name: 'Build: ${{ matrix.toolset }} / ${{ matrix.platform }} / ${{ matrix.configuration }}'
    defaults:
      run:
        shell: pwsh
    env:
      TOOLSET: '${{ matrix.toolset }}'
      PLATFORM: '${{ matrix.platform }}'
      CONFIGURATION: '${{ matrix.configuration }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: '${{ matrix.platform }}'
        if: matrix.toolset == 'mingw'
      - name: Build
        run: make install
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: 'privilege-check-${{ matrix.toolset }}-${{ matrix.platform }}-${{ matrix.configuration }}'
          path: '${{ runner.workspace }}/build/install/'
          if-no-files-found: error
