name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 5:30 AM on Sunday (somewhat randomly chosen).
    - cron: '30 5 * * 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # MinGW builds are done on Linux, since it's more up-to-date there, and
        # it's much faster.
        os: [ubuntu-20.04, windows-2016, windows-2019]
        platform: [x64, x86]
        configuration: [Debug, Release]
        include:
          - {os: windows-2016, toolset: msvc}
          - {os: windows-2019, toolset: msvc}
          - {os: ubuntu-20.04, toolset: mingw}
    runs-on: '${{ matrix.os }}'
    name: 'Build: ${{ matrix.os }} / ${{ matrix.toolset }} / ${{ matrix.platform }} / ${{ matrix.configuration }}'
    defaults:
      run:
        shell: pwsh
    env:
      TOOLSET: '${{ matrix.toolset }}'
      PLATFORM: '${{ matrix.platform }}'
      CONFIGURATION: '${{ matrix.configuration }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: '${{ matrix.platform }}'
        if: matrix.toolset == 'mingw'
      - name: Build
        run: make install
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: 'pdb-repo-${{ matrix.os }}-${{ matrix.toolset }}-${{ matrix.platform }}-${{ matrix.configuration }}'
          path: '${{ runner.workspace }}/build/install/'
          if-no-files-found: error
